import json

with open("adjacency.json", "r", encoding="utf-8") as f:
    data = json.load(f)

lines = []
lines.append("PETCLINIC DEPENDENCY GRAPH")
lines.append("Generated by P4 - Bhargavi")
lines.append("=" * 45)
lines.append(f"Total classes analysed : {len(data['all_classes'])}")
lines.append(f"Total dependency edges : {sum(len(v) for v in data['dependencies'].values())}")
lines.append("")

lines.append("Classes ranked by ripple impact:")
lines.append("")
ranked = sorted(data["dependents"].items(), key=lambda x: len(x[1]), reverse=True)
for i, (cls, used_by) in enumerate(ranked, 1):
    bar = "#" * len(used_by)
    lines.append(f"  {i:2}. {cls:35s} {len(used_by):3d} dependents  {bar}")

lines.append("")
lines.append("=" * 45)
lines.append("HERO DEMO — Owner full ripple map:")
lines.append("=" * 45)
for cls in data["dependents"].get("Owner", []):
    lines.append(f"  [AFFECTED] {cls}")

lines.append("")
lines.append("=" * 45)
lines.append("FULL DEPENDENCY MAP:")
lines.append("=" * 45)
for cls, deps in sorted(data["dependencies"].items()):
    if deps:
        lines.append(f"  {cls} --> {', '.join(deps)}")

report = "\n".join(lines)
print(report)

with open("summary.txt", "w", encoding="utf-8") as out:
    out.write(report)

print("\nsummary.txt saved.")